name: build

on: 
  push:
    branches:
      - 'main'

jobs:
  buildAndPublish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - name: setup python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install jupyter-book
      
      - name: build book
        run: |
          jupyter-book build .

      - name: github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html
          publish_branch: gh-pages